spring.application.name=dormhub_backend

# Use Render's database environment variables, fallback to local if not set
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/dormhub}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:sesame}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Secret
jwt.secret=jwt.secret=${JWT_SECRET:s8rLpXom3/9oh5aAWoAr3h1S/7+Bej0H5bomZcvV+zE=}